# Generated by Django 4.1.4 on 2022-12-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_is_active_alter_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
