# Generated by Django 4.1.4 on 2022-12-09 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_options_remove_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
