# Generated by Django 4.1.4 on 2022-12-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
